# Generated by Django 5.1 on 2024-08-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название фильма')),
                ('short_description', models.CharField(max_length=200, verbose_name='Жанр')),
                ('text', models.TextField(verbose_name='Описание фильма')),
                ('responce1', models.TextField(verbose_name='Популярный отзыв')),
                ('responce2', models.TextField(verbose_name='Отрицательный отзыв')),
                ('raiting', models.CharField(max_length=50, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
